### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by carobro** [carobro/Geosoftware2#40]
## Über die Ferien
- jeder versucht einmal die Dateien zu installieren
- Bei Problemen oder Fragen ein Issue erstellen und/oder sich in Mattermost melden

**Comment by carojw** [comment]
@nuest @edzer 

### Code Review by **CercaTrova** 
(@KathHv, @bennidietz, @carojw, @ipleis, @NiklasAsselmann) 
### for **Die Gruppe 1**
(@carobro, @JaFro96, @hilal98, @yhallowiegeht, @corneliazy) 


### I - Installation: 
Installation wurde getestet mit 64-bit Ubuntu 18.04 und hat so für Zenodo nicht funktioniert.. CLI Tools wie folgt: 

- `pip
install -r requirements.txt --user`
git und virtualenv führen zu Fehlern bei pip install:
> Could not find a version that satisfies the requirement git [...] 

- `apt-get install python-gdal`
`apt-get install gdal-bin`
`pip install pytest`
Funktioniert alles nur mit Rootrechten und führt so zu Fehlern

- > Dann kann in einer beliebigen, gängigen Konsole in den Ordner des Tools navigiert werden und
dort folgender Befehl ausgeführt werden 

Unklar wohin

- `python detailebenen.py --path="Der Path zur Datei"`
Test mit euren Testdateien (zB GML, GeoPackage):  
Error "not recognized as supported file format" kommt bei mehreren Testdateien, teilweise werden dann aber trotzdem Ergebnisse ausgegeben? 

- Wofür sind die Installationsanleitungen.md? Muss der User das installieren? 




### II - Code
**1. Code Formatting**
1.1. Using alignments (left margin) and proper white space, block starting point and ending point are identifiable easily
- ok, the blank spaces between paragraphs (also between blocks within functions) differ though which aggravates distinction between functions 

1.2. Proper naming conventions
- some functions are named in German, others in English **(must be in English)** ; different functions are named similarly
1.3. Code should fit in standard 14 inch laptop screen -> no horizontal scroll needed
- mostly okay
1.4. Sufficient code description / explanatory comments
- parts of the code are well explained in English (again, comments must be in English), others scarcely or not in an understandable fashion or not at all

2. Architecture
2.1. Code lies in appropriate folders
-Some files (i.e. detailebenen) are in two different folders? 
-There is a Metadatenextraktion folder within the Metadatenextraction folder? 
-Other than that okay

3. Coding best practice
3.1. Group similar values under an enumeration
- / 
3.2. Sufficient code description / explanatory comments, workarounds, temporary fixes, pending tasks (TODO's)
- As mentioned before, in parts good, other party scarcely/almost not commented

3.3. Avoiding multiple if/else blocks
- Multiple "try/catch" statements to determine datattype could probably be solved more elegantly 

3.4. Using framework features, wherever possible instead of writing custom code
- You use frameworks/libraries 

3.5. Additional comments
- You define a convex_hull function (and other similar example) twice within one file for the same parameters and again at other points instead of defining the function once and then reusing it


**4. Non-functional requirements**

4.1. Maintainability (App should require the least amount of effort to support in near future, should be easy to identify and to fix)
4.1.1. Readability (Code should be self-explanatory, using appropriate names for variables, functions and classes)
- varies a lot, at times good, other parts of the code/commentary need enhancement
4.1.2. Testability (Code should be easy to test)
- okay
4.1.3. Debuggability (Provide support to log the flow of control, parameter data and exception details to find the root cause easily)
- no problems found
4.1.4. Configurability (Keep the configurable values in place so that no code changes are required, if the data is changed frequently)
- you do have a config file, but don't use it for all variables

4.2. Reusability
4.2.1. DRY (Do not repeat yourself): same code should not be repeated more than twice
- See above, for example convex hull calculation
4.2.2. Consider reusable services, functions and components
- okay

4.3. Reliability
4.3.1 No not-used functions in the code
- okay

4.4. Extensibility
4.4.1. Easy to add enhancements with minimal changes to the existing code, one component should be easily replaceable by a better component 
- Same difficulty as mentioned before, other than that seems okay 

4.5. Performance
4.5.1. Use a data type that best suits the needs
- we couldn't find an actual approach to determining the similar records therefor hard to answer
